### ISSUE TITLE
You are not allowed to access this file (::ffff:172.22.0.4)

### ISSUE THREAD

**Issue by rmartis** [ambroisemaupate/docker-server-env#3]
`{"status":"fail","error":"You are not allowed to access this file (::ffff:172.22.0.4)."}`

172.22.0.X is container's IP and it's impossible to use neither `install.php` nor `clear_cache.php` on prod env
I had to remove check section from install.php and clear_cache.php.
I deleted `install.php` after installation process, but I don't want to delete `clear_cache.php`, but use it to cleaning cache; and now, anyone can do it......

Could you advice me or fix it?

**Comment by ambroisemaupate** [comment]
Hello @rmartis 

If you are using `traefik` reverse proxy with a Roadiz or other Symfony app restricting by IP. You should add first your IP address, here `::ffff:172.22.0.4` to your `dev.php`, `clear_cache.php`

Then, because `Traefik` **is** a Reverse proxy, you must comment the line where it rejects forwarded IP addresses too.

```php

$allowedIp = [
    '::ffff:172.22.0.4', // ADD HERE YOUR IP
    '127.0.0.1', 'fe80::1', '::1', ':ffff:127.0.0.1', '::ffff:127.0.0.1' // localhost
];

if (isset($_SERVER['HTTP_CLIENT_IP'])
//    || isset($_SERVER['HTTP_X_FORWARDED_FOR']) // COMMENT THIS LINE
    || !(in_array(@$_SERVER['REMOTE_ADDR'], $allowedIp) || php_sapi_name() === 'cli-server')
) {
    header('HTTP/1.0 403 Forbidden');
    exit('You are not allowed to access this file ('.$_SERVER['REMOTE_ADDR'].'). Check '.basename(__FILE__).' for more information.');
}
```

BTW, we are going to drop these protections on next Roadiz releases because we are more and more using Docker in dev and prod environments, and `dev.php` and `install.php` files are not included in production, so these protections are no longer valid and are so annoying when developing on local Docker env.
The only critical file is `clear_cache.php` which is copied into production env too, so we will need to keep restrincting IP for this file.

**Comment by rmartis** [comment]
Thank you
